# Generated by Django 4.1.2 on 2022-10-27 12:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
