# Generated by Django 4.1.2 on 2022-11-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_alter_programme_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='nb_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
