# Generated by Django 4.1.2 on 2024-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_programme_nb_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='font_family',
            field=models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Arial', 'Arial')], default='Times New Roman', max_length=50),
        ),
    ]
