# Generated by Django 4.1.2 on 2025-05-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_programme_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='font_family',
            field=models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Arial', 'Arial')], default='Arial', max_length=50),
        ),
    ]
